### ISSUE TITLE
小米 Android9系统试了一下，好像会报错

### ISSUE THREAD

**Issue by lycfr** [huanglqweiwei/PhoneMirror#1]
···
java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:500)
	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:135)
	at com.hlq.mobile.mini.MinicapReceiver.minicapRecord(MinicapReceiver.java:172)
	at com.hlq.mobile.mini.MinicapReceiver.run(MinicapReceiver.java:40)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
···
楼主可以帮忙解决一下吗

**Comment by huanglqweiwei** [comment]
可以看下命令行日志里面关于minicap的输出信息

**Comment by Chenjiang1** [comment]
我也遇到同样的·问题了 我给你看minicap的·输出信息吧
![image](https://user-images.githubusercontent.com/50128565/90006020-b5cf7d00-dcca-11ea-9310-078f429cc87c.png)

**Comment by Chenjiang1** [comment]
![image](https://user-images.githubusercontent.com/50128565/90006095-d8fa2c80-dcca-11ea-82ce-4a8688fe1558.png)

**Comment by Chenjiang1** [comment]
可以帮忙解决一下吗？

**Comment by huanglqweiwei** [comment]
![image](https://user-images.githubusercontent.com/21007339/90090128-cf69d680-dd55-11ea-85b6-ba64f7c2ab6c.png)
这个是minicap.so运行失败了，可以重启下手机试试

**Comment by huanglqweiwei** [comment]
@Chenjiang1 minicap上有这个类似问题：https://github.com/openstf/minicap/issues/169

**Comment by lycfr** [comment]
这个好像是miui系统会这样子。

**Comment by lycfr** [comment]
我试过好几次，重启也是会这样子。很奇怪

**Comment by huanglqweiwei** [comment]
@lycfr @Chenjiang1  https://github.com/openstf/minicap/issues/169#issuecomment-576180138 试试替换下这issue里面提到的minicap.so

**Comment by huanglqweiwei** [comment]
用这个[minicap-libgui.so](https://github.com/Orange-OpenSource/minicap/releases/download/v2.3.1/minicap-libgui.so)替换掉工程下面这个目录下的minicap.so试试：
![image](https://user-images.githubusercontent.com/21007339/90092408-73a24c00-dd5b-11ea-9912-24b1e8320868.png))

**Comment by Chenjiang1** [comment]
还是报错 我虽然把文件替换掉了，但是启动后文件又自动生成了

**Comment by Chenjiang1** [comment]
MinicapReceiver_reader : line = PID: 3674
MinicapReceiver_reader : line = INFO: Using projection 1080x2340@360x780/0
MinicapReceiver_reader : line = INFO: (external/MY_minicap/src/minicap_28.cpp:241) Creating SurfaceComposerClient
MinicapReceiver_reader : line = INFO: (external/MY_minicap/src/minicap_28.cpp:244) Performing SurfaceComposerClient in
it check
MinicapReceiver_reader : line = INFO: (external/MY_minicap/src/minicap_28.cpp:255) Creating virtual display
MinicapReceiver_reader : line = INFO: (external/MY_minicap/src/minicap_28.cpp:261) Creating buffer queue
MinicapReceiver_reader : line = INFO: (external/MY_minicap/src/minicap_28.cpp:264) Setting buffer options
MinicapReceiver_reader : line = INFO: (external/MY_minicap/src/minicap_28.cpp:268) Creating CPU consumer
MinicapReceiver_reader : line = INFO: (external/MY_minicap/src/minicap_28.cpp:272) Creating frame waiter
MinicapReceiver_reader : line = INFO: (external/MY_minicap/src/minicap_28.cpp:276) Publishing virtual display
MinicapReceiver_reader : line = Vector<> have different types (this=0x7ffecc8cf0, rhs=0x7ffecc8e10)
MinicapReceiver_reader : line = Aborted
MinicapReceiver : finish connect port = 1701
java.nio.BufferUnderflowException
        at java.nio.Buffer.nextGetIndex(Unknown Source)
        at java.nio.HeapByteBuffer.get(Unknown Source)
        at com.hlq.mobile.mini.MinicapReceiver.minicapRecord(MinicapReceiver.java:172)
        at com.hlq.mobile.mini.MinicapReceiver.run(MinicapReceiver.java:40)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Tools : executeShellCommand : rm /data/local/tmp/minicap

**Comment by Chenjiang1** [comment]
![image](https://user-images.githubusercontent.com/50128565/90096565-31323c80-dd66-11ea-8ba9-5812376652bf.png)

**Comment by Chenjiang1** [comment]
上面的代码是手机重启后再运行的

**Comment by huanglqweiwei** [comment]
@Chenjiang1 是替换，就是minicap-libgui.so要重命名为minicap.so

**Comment by Chenjiang1** [comment]
OK，万分感谢已经可以控制我的手机了，但是又出现了一个新的问题
窗口是白色的无法显示手机页面，点击下面的按钮可以正常反应

**Comment by Chenjiang1** [comment]
![image](https://user-images.githubusercontent.com/50128565/90100476-57100f00-dd6f-11ea-9827-8cd3fe44b784.png)

**Comment by huanglqweiwei** [comment]
`USB调试（安全设置）`打开了吗？在开发设置里面

**Comment by Chenjiang1** [comment]
安装 调试 安全设置 都打开了

**Comment by lycfr** [comment]
试一下关闭工具在打开试试，有时候是有点问题

**Comment by huanglqweiwei** [comment]
嗯，有的小米手机有时候第一次是显示不出来，重新打开一次就又显示了

**Comment by Chenjiang1** [comment]
重新启动工具/手机 都是一样显示不了 是不是我分辨率太高了 显示不了啊，我手机分辨率是2430*1080的

**Comment by huanglqweiwei** [comment]
你可以打日志调试下，看pc端有没有接收到从手机端发送过来的图片流

**Comment by lycfr** [comment]
@huanglqweiwei SingleTouch这个apk 我想单独使用，这个需要什么指令驱动起来？

**Comment by Chenjiang1** [comment]
ReceiveJpg : version = 1
ReceiveJpg : headLen = 24
ReceiveJpg : pid = 11210
ReceiveJpg : realWidth = 1080
ReceiveJpg : realHeight = 2340
ReceiveJpg : virWidth = 360
ReceiveJpg : virHeight = 780
ReceiveJpg : orientation = 0

**Comment by Chenjiang1** [comment]
是这个吗？

**Comment by huanglqweiwei** [comment]
@Chenjiang1 这里：https://github.com/huanglqweiwei/PhoneMirror/blob/16a128761ea96dcc98f840c89490d8c0dc1d7672/src/main/java/com/hlq/mobile/mini/MinicapReceiver.java#L198

**Comment by huanglqweiwei** [comment]
> @huanglqweiwei SingleTouch这个apk 我想单独使用，这个需要什么指令驱动起来？

@lycfr 关于这个apk的使用都在这里类里面：https://github.com/huanglqweiwei/PhoneMirror/blob/16a128761ea96dcc98f840c89490d8c0dc1d7672/src/main/java/com/hlq/mobile/mini/SingleTouch.java#L14

**Comment by lycfr** [comment]
> > @huanglqweiwei SingleTouch这个apk 我想单独使用，这个需要什么指令驱动起来？
> 
> @lycfr 关于这个apk的使用都在这里类里面：
> 
> https://github.com/huanglqweiwei/PhoneMirror/blob/16a128761ea96dcc98f840c89490d8c0dc1d7672/src/main/java/com/hlq/mobile/mini/SingleTouch.java#L14

我看你用到了app_process，但是前面有个端口转换adb forward操作，然后分别去监听端口获取数据是吧

**Comment by Chenjiang1** [comment]
debug了一下 并没有执行这行代码
minicapRecord这个方法都没有执行，原因是
![image](https://user-images.githubusercontent.com/50128565/90102258-c76c5f80-dd72-11ea-9949-d9e31fd2b963.png)

**Comment by huanglqweiwei** [comment]
@lycfr 嗯，是的，apk在手机端运行的时候会起一个Server，pc端作为client去连这个Server，后面就通过这个连接与手机端进行通信，发送指令给手机端执行

**Comment by huanglqweiwei** [comment]
> debug了一下 并没有执行这行代码
> minicapRecord这个方法都没有执行，原因是
> ![image](https://user-images.githubusercontent.com/50128565/90102258-c76c5f80-dd72-11ea-9949-d9e31fd2b963.png)

@Chenjiang1 那可能是minicap没有发送图片流信息出来

**Comment by lycfr** [comment]
> @lycfr 嗯，是的，apk在手机端运行的时候会起一个Server，pc端作为client去连这个Server，后面就通过这个连接与手机端进行通信，发送指令给手机端执行

@huanglqweiwei 我搞出来了，谢谢了

**Comment by Chenjiang1** [comment]
作者您好，我想问下，如果我想拿到连接手机后，这个手机的图片流信息应该在哪里拿呢？

**Comment by Chenjiang1** [comment]
![image](https://user-images.githubusercontent.com/50128565/90210409-73b84f80-de20-11ea-863a-ba41075f84ab.png)
这个方法可以吗？

**Comment by Chenjiang1** [comment]
prepareMinicap()

**Comment by huanglqweiwei** [comment]
@Chenjiang1 这里：
![image](https://user-images.githubusercontent.com/21007339/90217232-622c7300-de33-11ea-94d7-66e40ea8ccef.png)
https://github.com/huanglqweiwei/PhoneMirror/blob/16a128761ea96dcc98f840c89490d8c0dc1d7672/src/main/java/com/hlq/mobile/view/Mirror.java#L161

**Comment by Chenjiang1** [comment]
作者大大，我想问下如何才能连接多个手机啊？是启动一个PhoneMirror就可以连接多个手机了吗？还是说要改代码？，如果是启动一个PhoneMirror就可以连接多个手机了，那请问如何能区分各个手机的图片输入流呢？

**Comment by huanglqweiwei** [comment]
。。。adb devices能识别到几个手机，界面上就会显示几个手机，然后每打开一个手机的投屏画面就会创建一个Mirror 对象，可以根据Mirror对象区分不同手机

**Comment by Chenjiang1** [comment]
OK！知道了谢谢，还有个问题，我的想法是，监测到连接设备后自动获取手机的投屏画面（而不是需要点击一次连接的设备），应该怎么做呢？作者大大

> 。。。adb设备能识别到几个手机，界面上就会显示几个手机，然后每打开一个手机的投屏画面就会创建一个Mirror对象，可以根据Mirror对象区分不同手机

**Comment by huanglqweiwei** [comment]
可以在这个里面做：https://github.com/huanglqweiwei/PhoneMirror/blob/16a128761ea96dcc98f840c89490d8c0dc1d7672/src/main/java/com/hlq/mobile/Application.java#L87

**Comment by Chenjiang1** [comment]
知道了谢谢

**Comment by qinjiandong2010** [comment]
@huanglqweiwei @Chenjiang1 
各位大大，华为 P30 安卓版本10，运行页面空白，这是什么问题呢？

运行日志：
Application : adb Path = D:\Program Files (x86)\Androids\adb
Application : windowOpened
![image](https://user-images.githubusercontent.com/4538958/96667961-ae90b380-138c-11eb-8f16-f6d05216e258.png)

**Comment by huanglqweiwei** [comment]
处理方法见：https://github.com/huanglqweiwei/PhoneMirror/issues/1#issuecomment-673230498
