### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Chenjiang1** [huanglqweiwei/PhoneMirror#2]
使用小米手机（安卓九的系统），启动项目后无报错信息，但是phoneMirror窗口为空白

**Comment by qinjiandong2010** [comment]
> 使用小米手机（安卓九的系统），启动项目后无报错信息，但是phoneMirror窗口为空白

我也遇到了，你解决了吗？

**Comment by huanglqweiwei** [comment]
Duplicate of #1
